#!/usr/bin/env node
/**
 * Reads Foundry build artifacts and deployment JSON from ../paylink-contract,
 * and writes typed TS files into src/lib/contracts/.
 *
 * Usage: `pnpm sync:abi` (or `node scripts/sync-abi.ts` with tsx).
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs'
import { join, resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const CONTRACT_DIR = resolve(__dirname, '..', '..', 'paylink-contract')
const OUT_DIR = resolve(__dirname, '..', 'src', 'lib', 'contracts')

const ARTIFACTS: Record<string, string> = {
  InvoiceFactory: 'InvoiceFactory.sol/InvoiceFactory.json',
  InvoiceVault: 'InvoiceVault.sol/InvoiceVault.json',
  IERC3009: 'IERC3009.sol/IERC3009.json',
}

function readArtifactAbi(contract: string, artifactPath: string): unknown {
  const full = join(CONTRACT_DIR, 'out', artifactPath)
  if (!existsSync(full)) {
    throw new Error(`Foundry artifact not found for ${contract} at ${full}. Run \`forge build\` in ${CONTRACT_DIR} first.`)
  }
  const raw = JSON.parse(readFileSync(full, 'utf-8')) as { abi?: unknown }
  if (!raw.abi) throw new Error(`No abi field in ${full}`)
  return raw.abi
}

function readDeployments(): Record<string, Record<string, string>> {
  const dir = join(CONTRACT_DIR, 'deployments')
  const out: Record<string, Record<string, string>> = {}
  if (!existsSync(dir)) return out
  for (const f of readdirSync(dir)) {
    if (!f.endsWith('.json')) continue
    const chainId = f.replace('.json', '')
    try {
      const data = JSON.parse(readFileSync(join(dir, f), 'utf-8'))
      out[chainId] = {
        factory: data.factory ?? '',
        cUSD: data.cUSD ?? '',
        USDT: data.USDT ?? '',
      }
    } catch (err) {
      console.warn(`[sync-abi] skipping bad deployment file ${f}:`, err)
    }
  }
  return out
}

function main() {
  mkdirSync(OUT_DIR, { recursive: true })

  // ABIs
  const abiLines: string[] = [
    '// AUTO-GENERATED by scripts/sync-abi.ts. Do not edit by hand.',
    '',
  ]
  for (const [contract, rel] of Object.entries(ARTIFACTS)) {
    const abi = readArtifactAbi(contract, rel)
    abiLines.push(`export const ${contract}Abi = ${JSON.stringify(abi, null, 2)} as const`)
    abiLines.push('')
  }
  writeFileSync(join(OUT_DIR, 'abi.ts'), abiLines.join('\n'))

  // Addresses
  const deployments = readDeployments()
  const addrLines: string[] = [
    '// AUTO-GENERATED by scripts/sync-abi.ts. Do not edit by hand.',
    '',
    'export type ChainAddresses = {',
    '  factory: `0x${string}` | ""',
    '  cUSD: `0x${string}` | ""',
    '  USDT: `0x${string}` | ""',
    '}',
    '',
    'export const addresses: Record<number, ChainAddresses> = {',
  ]
  for (const [chainId, a] of Object.entries(deployments)) {
    addrLines.push(`  ${chainId}: {`)
    addrLines.push(`    factory: '${a.factory}' as any,`)
    addrLines.push(`    cUSD: '${a.cUSD}' as any,`)
    addrLines.push(`    USDT: '${a.USDT}' as any,`)
    addrLines.push('  },')
  }
  // Always include placeholders for known chainIds so the app still compiles before first deploy.
  for (const cid of ['11142220', '42220']) {
    if (!deployments[cid]) {
      addrLines.push(`  ${cid}: {`)
      addrLines.push(`    factory: '' as const,`)
      addrLines.push(
        `    cUSD: '${cid === '11142220' ? '0xdE9e4C3ce781b4bA68120d6261cbad65ce0aB00b' : '0x765DE816845861e75A25fCA122bb6898B8B1282a'}' as any,`,
      )
      addrLines.push(
        `    USDT: '${cid === '11142220' ? '0xd077A400968890Eacc75cdc901F0356c943e4fDb' : '0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e'}' as any,`,
      )
      addrLines.push('  },')
    }
  }
  addrLines.push('}')
  addrLines.push('')
  addrLines.push(
    "export function getAddresses(chainId: number): ChainAddresses { return addresses[chainId] ?? { factory: '', cUSD: '', USDT: '' } }",
  )
  writeFileSync(join(OUT_DIR, 'addresses.ts'), addrLines.join('\n'))

  console.log('[sync-abi] wrote', OUT_DIR + '/abi.ts')
  console.log('[sync-abi] wrote', OUT_DIR + '/addresses.ts')
}

main()
